sudo: required
dist: trusty

language: cpp
os:
  - linux

before_script:
  - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
  - sudo sed -i 's/trusty/wily/g' /etc/apt/sources.list
  - sudo sed -i 's/trusty/wily/g' /etc/apt/sources.list.d/kubuntu-ppa-backports-trusty.list
  - sudo apt-get -y -qq install libkf5i18n-dev libkf5notifications-dev libkf5service-dev libkf5windowsystem-dev plasma-framework-dev qtbase5-dev qtdeclarative5-dev extra-cmake-modules cmake g++
  - rm -rf build
  - mkdir build

script:
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ../sources
  - make
